### ISSUE TITLE
android.os.TransactionTooLargeException

### ISSUE THREAD

**Issue by hyakuri-git** [trevjonez/composer-gradle-plugin#10]
Not sure if I should be opening this here or on the composer page, let me know.
Opened it here because I am using the gradle plugin.

This is occurring when the test run finishes after running on one emulator. Not sure if this is due to the large amount of test failures. A previous run (with an emulator and hardware device) hung on finish rather than crashed. XML file was generated with that run, but not with this one.

> 12-28 11:19:30.964 2193-2208/com.x.x I/TestRunner: run finished: 88 tests, 65 failed, 0 ignored
> 12-28 11:19:31.158 2193-2204/com.x.x I/art: Background partial concurrent mark sweep GC freed 27832(2MB) AllocSpace objects, 199(69MB) LOS objects, 3% free, 115MB/119MB, paused 1.931ms total 170.351ms
> 12-28 11:19:31.318 2193-2208/com.x.x I/MonitoringInstr: waitForActivitiesToComplete() took: 0ms
> 12-28 11:19:31.319 2193-2193/com.x.x I/MonitoringInstr: Activities that are still in CREATED to STOPPED: 0
> 12-28 11:19:31.333 2193-2204/com.x.x I/art: Background partial concurrent mark sweep GC freed 8335(386KB) AllocSpace objects, 9(27MB) LOS objects, 2% free, 149MB/153MB, paused 2.077ms total 159.803ms
> 12-28 11:19:31.338 2193-2208/com.x.x E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 13370232)
> 12-28 11:19:31.339 2193-2208/com.x.x E/AndroidRuntime: FATAL EXCEPTION: Instr: android.support.test.runner.AndroidJUnitRunner
>                                                                        Process: com.x.x, PID: 2193
>                                                                        java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 13370232 bytes
>                                                                            at android.app.ActivityThread.finishInstrumentation(ActivityThread.java:5385)
>                                                                            at android.app.Instrumentation.finish(Instrumentation.java:213)
>                                                                            at android.support.test.runner.MonitoringInstrumentation.finish(MonitoringInstrumentation.java:330)
>                                                                            at android.support.test.runner.AndroidJUnitRunner.finish(AndroidJUnitRunner.java:395)
>                                                                            at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:384)
>                                                                            at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1932)
>                                                                         Caused by: android.os.TransactionTooLargeException: data parcel size 13370232 bytes
>                                                                            at android.os.BinderProxy.transactNative(Native Method)
>                                                                            at android.os.BinderProxy.transact(Binder.java:615)
>                                                                            at android.app.ActivityManagerProxy.finishInstrumentation(ActivityManagerNative.java:4531)
>                                                                            at android.app.ActivityThread.finishInstrumentation(ActivityThread.java:5383)
>                                                                            at android.app.Instrumentation.finish(Instrumentation.java:213) 
>                                                                            at android.support.test.runner.MonitoringInstrumentation.finish(MonitoringInstrumentation.java:330) 
>                                                                            at android.support.test.runner.AndroidJUnitRunner.finish(AndroidJUnitRunner.java:395) 
>                                                                            at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:384) 
>                                                                            at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1932)

**Comment by trevjonez** [comment]
not sure that this is related to either of them. AFAIK composer doesn't have an android runtime component nor does the gradle plugin. I would recommend investigating your own app/test code. stack trace seems inconclusive of source of large data causing the exception

**Comment by hyakuri-git** [comment]
Doh, you're totally right. I probably should have tried connectedDebugAndroidTest before posting. Not really aware of any changes (went from working to not working with no new test commits), but it's definitely not composer.

Sorry.
