### ISSUE TITLE
How to specify tests size?

### ISSUE THREAD

**Issue by juliocbcotta** [trevjonez/composer-gradle-plugin#12]
Hi, is it possible to have gradle tasks for tests size? Like... with spoon we can `spoonDebugAndroidTestSmall` so it runs just the tests annotates with `@SmallTest`

**Comment by trevjonez** [comment]
based on the [android InstrumentationTestRunner docs](https://developer.android.com/reference/android/test/InstrumentationTestRunner.html) it should be something like the following:

`instrumentationArgument('size', 'small')`

using that in the correct location should give you what you need.
