### ISSUE TITLE
Feature-Request: ability to have a global config

### ISSUE THREAD

**Issue by ligi** [trevjonez/composer-gradle-plugin#19]
Currently you have to configure per variant - it would be great to be able to configure globally.
Especially interested in configuring apkInstallTimeout in a DRY way

**Comment by trevjonez** [comment]
I am thinking of adding more options to the root dsl object to resolve this. that will act as the global but the variants would override the root global config if different.

`shard`, `verboseOutput`, `device`, `devices`, `devicePattern`, `apkInstallTimeout`.

A possible workaround until I can do this work would be to use the `tasks.all { ... }` to find the tasks that match the composer task pattern and update the configuration of said task with your global setting.

**Comment by ligi** [comment]
sounds great - thanks!

**Comment by trevjonez** [comment]
in 0.8.0 and the readme dsl overview has a few adjustment to show the changes. I bit better doc block on the sources too.
