### ISSUE TITLE
Add documentation around using `instrumentationArgument` DSL method, and why you would.

### ISSUE THREAD

**Issue by JankoCvirn** [trevjonez/composer-gradle-plugin#20]
It would be great if one could define a specific class that has to be run or is it already possible?

**Comment by trevjonez** [comment]
You can do it already with the `instrumentationArgument` method in the configuration DSL. I don't think you are the first person to ask so perhaps this is a call for some better info on the readme file.

For now, [here is a link to the InstrumentationTestRunner documentation] (https://developer.android.com/reference/android/test/InstrumentationTestRunner) so you can figure out what to pass to it.
