### ISSUE TITLE
output files generated in the project folder

### ISSUE THREAD

**Issue by CristianGM** [trevjonez/composer-gradle-plugin#26]
there are a los of `.output` files generated on the project folder ( later cleaned ), they should be in any temporary folder inside `build`.

**Comment by trevjonez** [comment]
This one may be hard. IIRC composer just puts them in the directory from which it was invoked without option to control placement. we may need to PR them.

**Comment by trevjonez** [comment]
blocked by https://github.com/gojuno/composer/issues/13

**Comment by trevjonez** [comment]
> in the directory from which it was invoked

Maybe I could use `setWorkingDir` on the javaExec task to force it into the build dir? 🤔

**Comment by trevjonez** [comment]
Guess I don't have a good excuse for this one now that we hard forked the upstream tools.
