### ISSUE TITLE
Upgrade composer to 0.4.0

### ISSUE THREAD

**Issue by lct8712** [trevjonez/composer-gradle-plugin#30]
Composer has released 0.4.0:
https://github.com/gojuno/composer/releases
Maybe upgrade the default version in gradle plugin from 0.3.0 to 0.4.0.

**Comment by trevjonez** [comment]
composer is selected via normal gradle dependency management via the 'composer' configuration on which ever project a task/plugin is applied so you can override the behavior. 

once we get #28 merged i'll put out a new version with everything bumped to latest stable all around. really 28 is pre-req to usable orchestrator support anyway.

**Comment by trevjonez** [comment]
try 0.9.0
