### ISSUE TITLE
Publish plugin on gradlePluginPortal / mavenCentral

### ISSUE THREAD

**Issue by plastiv** [trevjonez/composer-gradle-plugin#32]
`jitpack` is good for rapid development and prototyping. Do you think at this point plugin is stable enough to be published on proper artifact registry?

**Comment by trevjonez** [comment]
yea I will probably push it to the gradle portal. it is mostly simple to setup without odd constraints. I do intend to keep the repo jitpack friendly though so local fixes and forks can iterate rapidly, etc...

**Comment by trevjonez** [comment]
I added a branch with the config for plugin portal publishing just now. I'll try to get it up there for version 0.10.0

**Comment by trevjonez** [comment]
so it looks like the plugin portal doesn't like the lib module that doesn't itself contain a plugin impl. I'll either have to merge the two or go with a different repo. leaning towards merging the two. I don't think there is much use case of core alone to date.

**Comment by trevjonez** [comment]
targeting 0.11 for this.

**Comment by trevjonez** [comment]
![image](https://user-images.githubusercontent.com/5386503/55208348-8b4b5580-51a3-11e9-8bfd-f3f4d5b46f4c.png)
