### ISSUE TITLE
instrumentation-arguments are broken on Gradle 5.0

### ISSUE THREAD

**Issue by CristianGM** [trevjonez/composer-gradle-plugin#33]
We have found errors on our builds after updating to Gradle 5.0, we had:
`instrumentationArgument('notAnnotation', 'android.support.test.filters.FlakyTest')`
to ignore tests with that annotation ( until we fix or delete them ), but we saw it's running them now.

I ran the tests of the plugin and everything worked until I added `.withGradleVersion("5.0")` to `GradleRunner.create()` on ComposerPluginTest.

Now this test fails:
> com.trevjonez.composer.ComposerPluginTest#plugin cascades and collects dsl inputs
with the error:
```
to contain:
 <["--instrumentation-arguments, screenshotsDisabled, false, screenshotsEngine, uiAutomator, --verbose-output, true, --keep-output-on-exit, --install-timeout, 10",
    "Successfully installed apk",
    "Starting tests",
    "Test run finished, 0 passed, 0 failed",
    "Error: 0 tests were run."]>
but could not find:
 <["--instrumentation-arguments, screenshotsDisabled, false, screenshotsEngine, uiAutomator, --verbose-output, true, --keep-output-on-exit, --install-timeout, 10"]>
```

actually the only thing missing is `--instrumentation-arguments, screenshotsDisabled, false, screenshotsEngine, uiAutomator, `

Using the version 0.7.0 of the plugin it works fine ( if you don't need Orchestrator or any other feature added later ), but 0.8.0 or newer fails.

**Comment by trevjonez** [comment]
@CristianGM can I get your 👀 on that pr just to see if I missed anything obvious to this issue?
