### ISSUE TITLE
Setup some real CI for this project. That is what it is all about after all.

### ISSUE THREAD

**Issue by trevjonez** [trevjonez/composer-gradle-plugin#36]
Need to have a CI script run through the various versions of AGP and Gradle so the known supported combination stays good.

**Comment by plastiv** [comment]
I am interested in GitHub Actions to check what the fuzz is about. I can prototype something simple for a start. For example to just compile project with Gradle assemble and then expand from there. Are you interested in GitHub Actions or thinking about something else like Travis as a base?

**Comment by trevjonez** [comment]
Actions sounds great to me. PR away!

**Comment by trevjonez** [comment]
as a part of #59 I may see if I can figure out a reasonable way to record adb interactions to stub that external behavior in tests making TDD easier. At current the tests require a device be connected, which sucks for a lack of better terms. Both stubs or real externals should be an option for dev/regression checking. May be a good way to deal with backward compat of different tool chain version combo's.
