### ISSUE TITLE
AGP + Gradle conflict

### ISSUE THREAD

**Issue by tir38** [trevjonez/composer-gradle-plugin#43]
I'm about to update to 0.11.1 and I'm going through all the needed changes. I see in the readme

Composer plugin version | Gradle version | Android plugin version
| ------  | ------             | ------ |
| 0.11.*  | 5.3.1              | 3.3.2, 3.5.0-alpha09<sup>\*</sup>  

However AGP 3.3.2 doesn't "come" with Gradle 5.3.1. I would have to manually update my `gradle-wrapper.properties`. Is this something that you are advocating for?

**Comment by trevjonez** [comment]
Yes absolutely, I strongly recommend that every project uses the latest Gradle version always. It is a very good way to not end up with huge amounts of migration work that everyone is afraid to do.

**Comment by tir38** [comment]
OK we are keeping up with latest beta AGP and whichever version of Gradle it wants to update too. But we have not been bumping Gradle version on its own.

**Comment by trevjonez** [comment]
Let me know if you see any other issues.
