### ISSUE TITLE
Tests duplication and wrong count

### ISSUE THREAD

**Issue by aleien** [trevjonez/composer-gradle-plugin#47]
Hello! 

First of all, thank you very mush for developing this plugin!

We are actively writing tests for our app and decided we could use some parallel execution. We set up composer, but we're experiencing some issues with tests count. We have 365 tests (not counting parametrized as separate tests), but running them with composer gives us difference results each time.

**Examples:**
Original
![image](https://user-images.githubusercontent.com/7263920/58868669-76b89b80-86c5-11e9-9b25-3b361324e923.png)

Composer run 1
![image](https://user-images.githubusercontent.com/7263920/58868699-8801a800-86c5-11e9-83e2-582becfa13e8.png)

Composer run 2 (same branch)
![image](https://user-images.githubusercontent.com/7263920/58868720-95b72d80-86c5-11e9-85fa-695509e7b53f.png)

Seems like there are appearing some duplicating tests with 0 time length
![image](https://user-images.githubusercontent.com/7263920/58870713-64d8f780-86c9-11e9-8656-ff0ece2e03d5.png)
![image](https://user-images.githubusercontent.com/7263920/58870942-cb5e1580-86c9-11e9-8e6d-5de0999c2102.png)

**Our setup:**
Composer plugin v.10.0
Gradle 5.1.1
Android Build Tools 3.3.0

junit4
parametrized tests
orchestrator (support version)

Composer setup
```composer {
    instrumentationArgument("clearPackageData", "true")
    configs {
        devDebug {
            withOrchestrator true
            outputDirectory project.properties['test.reports.dir'] + "/composer"
        }
    }
}
```

Although, it seems more like composer problem ): Could you, please, tell what version of composer are you using for plugin v10.0?

**Comment by trevjonez** [comment]
version 0.10.0 was using 0.5.0
you might try again with version 0.12.0 which uses 0.6.0 (will force you to AGP 3.4.1)
or add the higher version to the composer configurations
```
dependencies {
 composer "com.gojuno.composer:composer:0.6.0"
}
```

also make sure you tell composer about the orchestrator via
```
composer {
  withOrchestrator true
}
```

**Comment by aleien** [comment]
Thanks for fast reply!

Won't that force us to use androidX orchestrator?

**Comment by trevjonez** [comment]
I believe you are correct it would force an update to androidX. I do recommend you update as soon as possible though. Going to close this for now is there is nothing actionable for this repo as of now.
I may be worth checking or creating an issue directly on composer. https://github.com/gojuno/composer/issues
