### ISSUE TITLE
Clear screenshots

### ISSUE THREAD

**Issue by tir38** [trevjonez/composer-gradle-plugin#48]
There is talk about old screenshots piling up on Composer https://github.com/gojuno/composer/issues/150. @trevjonez you talk about just adding a second step to wipe them https://github.com/gojuno/composer/issues/150#issuecomment-397653671

Instead of waiting around for Composer to fix this, any chance you'd actually add the step to the Gradle plugin?

**Comment by trevjonez** [comment]
The gradle plugin is really only intended to be a DSL driven replacement for the CLI they provide. Let me see if I can set aside some time to port what I did in my other project to add it straight to composer.

**Comment by trevjonez** [comment]
well I laid the work down, not sure how it will go as my two PR's are pretty hefty, but we will see. Closing this issue now that we have pushed the paper trail down onto the repo's that own the code.
