### ISSUE TITLE
How to take screenshot with Composer and Espresso Android.

### ISSUE THREAD

**Issue by herbert-soares-ifood** [trevjonez/composer-gradle-plugin#49]
Hello.
How to take screenshot with Composer with Gradle And Espresso Android?

My code on gradle:
composer {
  instrumentationArgument('notAnnotation', 'com.trevjonez.kontrast.KontrastTest')
  withOrchestrator true
  shard true
  instrumentationArgument('screenshotsDisabled', 'false')
  configs {
    debug {
      instrumentationArgument('screenshotsEngine', 'uiAutomator')
      keepOutput true
    }
  }
} 

And i utilize version 0.12.0

**Comment by herbert-soares-ifood** [comment]
This don`t take screenshot and don`t upload for report. html

**Comment by gabriel-prado-ifood** [comment]
up

**Comment by rafael-hiroshi-ifood** [comment]
Up

**Comment by trevjonez** [comment]
nothing actionable here for the gradle plugin.
