### ISSUE TITLE
Provide report file name

### ISSUE THREAD

**Issue by plastiv** [trevjonez/composer-gradle-plugin#5]
Feature request. 

I found it useful to have report filename printed, because then it is easy to navigate from terminal by just clicking it. Like lint and spoon runner does. Let me know if you think this addition would fit your vision of plugin development.

![image](https://user-images.githubusercontent.com/179550/30987912-e74fac3c-a498-11e7-9bf8-63989b322acc.png)

**Comment by trevjonez** [comment]
yes absolutely fits. should be super simple to add as well.

**Comment by trevjonez** [comment]
Give [version 0.3.0](https://github.com/trevjonez/composer-gradle-plugin/releases/tag/0.3.0) or the latest [AGP-3.0.0-SNAPSHOT](https://jitpack.io/#trevjonez/composer-gradle-plugin/AGP-3.0.0-SNAPSHOT) a try.
