### ISSUE TITLE
Take Screenshot for Report With Composer.

### ISSUE THREAD

**Issue by loadin799** [trevjonez/composer-gradle-plugin#50]
How to take screenshot and upload on Report Composer?

**Comment by herbert-soares-ifood** [comment]
up

**Comment by trevjonez** [comment]
composer pulls screenshots produced by spoon's runtime library.
falcon can be used with spoon to get more complete screenshots
or you can have ui automator write to the file produced by spoon to get an even better shot.
there is also a library https://github.com/Muddz/PixelShot that could be used.

none of this has anything to do with the gradle plugin though so I am closing the issue.
