### ISSUE TITLE
Question - maintained

### ISSUE THREAD

**Issue by dannybduval** [trevjonez/composer-gradle-plugin#56]
Out of curiosity, I noticed that [composer](https://github.com/gojuno/composer) is now archived, will this be archived as well?

Just curious as there will likely be a need for ongoing base support that the plug in may not be able to support.

**Comment by trevjonez** [comment]
I saw that too. I have not decided what the best course of action is for this project as of yet. Initially I was thinking to follow suit and archive as my current schedule doesn't allow for me to add much more. 

Although I worry that would leave a large number of projects jettisoned without a replacement. 

So for now I will continue supporting at the least the gradle plugin, and contemplate publishing a fork of commander/composer to use as the default impl with the plugin until a suitable replacement and migration strategy can be published.

**Comment by trevjonez** [comment]
https://github.com/trevjonez/composer-gradle-plugin#project-status
