### ISSUE TITLE
Problem with gradle 6.4

### ISSUE THREAD

**Issue by ligi** [trevjonez/composer-gradle-plugin#77]
after switching to gradle 6.4 I am seeing this issue:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:testNoGethForFDroidOfflineDebugComposer'.
> The value for task ':app:testNoGethForFDroidOfflineDebugComposer' property 'mainClass' is final and cannot be changed any further.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3m 1s
```

**Comment by trevjonez** [comment]
give [rc07](https://github.com/trevjonez/composer-gradle-plugin/releases/tag/1.0.0-rc07) a spin and let me know if you still hit issues and we can debug further if need be.

**Comment by ligi** [comment]
oh nice - there is work on 6.4 support already - great!
Unfortunately it seems there is a build fail for the 1.0.0-rc series on jitpack: https://jitpack.io/com/github/trevjonez/composer-gradle-plugin/1.0.0-rc07/build.log

**Comment by trevjonez** [comment]
Not sure how jitpack could have worked after we had to pull in composer. The NPM dependency isn't going to run there.

You will need to update your configuration to use jcenter and the gradlePluginPortal

**Comment by trevjonez** [comment]
I am going to go ahead and close this. While jitpack is typically a super convenient tool, this project no longer fits within its prescribed build chain cleanly.

Recommendation moving forward is to update import coordinates to utilize jcenter.
